apiVersion: v1
kind: Namespace
metadata:
  name: petstore
---
apiVersion: v1
kind: Service
metadata:
  name: petstore
  namespace: petstore
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: http-port
      protocol: TCP
  selector:
    app: petstore     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petstore
  namespace: petstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petstore
  template:
    metadata:
      labels:
        app: petstore
    spec:
      containers:
      - name: petstore
        image: quay.io/kuadrant/petstore3:1.0.12
        imagePullPolicy: Always
        ports:
          - name: http-port
            containerPort: 8080
            protocol: TCP
        env:
          - name: REGION
            valueFrom:
              configMapKeyRef:
                name: cluster-config
                key: REGION
---
apiVersion: v1
kind: Secret
metadata:
  name: petstore-api-key
  namespace: petstore
  labels:
    authorino.kuadrant.io/managed-by: authorino
    kuadrant.io/apikeys-by: api_key
stringData:
  api_key: secret
type: Opaque
